import type { Metadata } from "next";
import { Anton, Roboto } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";
import NavComponent from "@/components/nav/header";

const geistRoboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto'
})

const geistAnton= Anton({
  weight: ['400'],
  subsets: ["latin"],
  display: 'swap',
  variable: "--font-anton",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistRoboto.variable} ${geistAnton.variable}`}>
        <Providers>
          <NavComponent/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
